name: Build and Push Web Admin to GCP Artifact Registry (DEV)

on:
  pull_request:
    branches:
      - dev

env:
  IMAGE_VERSION: '0.0.0001'
  IMAGE_NAME: dev-kashless
  IMAGE_BASE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/club-tijuana-docker-repo/

jobs:
  build-and-push-gar:
    name: Build and push Docker image to Artifact Registry
    runs-on: ubuntu-latest
    environment: GCP_DEV

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GCP_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Extract Docker metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_BASE }}${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,prefix=dev-
            type=raw,value=dev-latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Odasoft.XBOL.AdminPortal/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

